<a href="https://colab.research.google.com/github/mazdah/colab_practice/blob/main/%ED%8C%A8%EC%8A%A4%ED%8A%B8%EC%BA%A0%ED%8D%BC%EC%8A%A4_%EC%A7%81%EC%9E%A5%EC%9D%B8%EC%9D%84_%EC%9C%84%ED%95%9C_%ED%8C%8C%EC%9D%B4%EC%8D%AC_%EB%8D%B0%EC%9D%B4%ED%84%B0%EB%B6%84%EC%84%9D.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [ ]:
np

<module 'numpy' from '/usr/local/lib/python3.7/dist-packages/numpy/__init__.py'>

In [ ]:
arr = np.array([1, 2, 3, 4], dtype=int)

In [ ]:
arr

array([1, 2, 3, 4])

In [ ]:
type(arr)

numpy.ndarray

In [ ]:
mylist1 = [1, 2, 3, 4]

In [ ]:
mylist2 = [[1, 2, 3, 4],
           [5, 6, 7, 8]]

In [ ]:
arr1 = np.array(mylist1)
arr2 = np.array(mylist2)

In [ ]:
arr1.shape

(4,)

In [ ]:
arr2.shape

(2, 4)

- list는 서로 다른 데이터 타입이 함께 조재할 수 있으나
- array는 모든 요소의 데이터 타입이 동일해야 한다

In [ ]:
mylist = [1, 3.14, "문자열", (2, 3)]

In [ ]:
mylist

[1, 3.14, '문자열', (2, 3)]

In [ ]:
type(mylist)

list

In [ ]:
arr = np.array([1, 2, 3.14, 2.12])

In [ ]:
arr

array([1.  , 2.  , 3.14, 2.12])

In [ ]:
arr2 = np.array([1, 2, 3.14, 2.12], dtype=int)

In [ ]:
arr2

array([1, 2, 3, 2])

In [ ]:
arr3 = np.array([1, 2, "3.14", 2.12])

In [ ]:
arr3

array(['1', '2', '3.14', '2.12'], dtype='<U21')

In [ ]:
arr3 = np.array([1, 2, "3.14", 2.12], dtype=int)

ValueError: ignored

In [ ]:
arr3 = np.array([1, 2, "1234", 2.12], dtype=int)

In [ ]:
arr3

array([   1,    2, 1234,    2])

In [ ]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr.shape

(10,)

# index를 이용한 색인 

In [ ]:
arr[-1]

9

In [ ]:
arr[-11]

IndexError: ignored

In [ ]:
arr2d = np.array([[1, 2, 3, 4],
         [5, 6, 7, 8],
         [9, 10, 11, 12]])

In [ ]:
arr2d[1, 1]

6

---
# 범위 색인

In [ ]:
arr[3:]

array([3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr[:5]

array([0, 1, 2, 3, 4])

In [ ]:
arr[1:5]

array([1, 2, 3, 4])

In [ ]:
arr[:-1]

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
arr2d[1, :]

array([5, 6, 7, 8])

In [ ]:
arr2d[:, 1]

array([ 2,  6, 10])

In [ ]:
arr2d[:2, :]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
arr2d[1:, :2]

array([[ 5,  6],
       [ 9, 10]])

---
# 팬시 인덱싱

In [3]:
arr = np.array([10, 28, 2, 7, 90, 65, 22, 66, 70])

In [4]:
idx = [1, 3, 5]

In [5]:
arr[idx]

array([28,  7, 65])

In [6]:
arr2d = np.array([[1, 2, 3, 4],
                  [5, 6, 7, 8],
                  [9, 10, 11, 12]])

In [7]:
arr2d[[0, 1], :]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [8]:
arr2d[:, [1,2,3]]

array([[ 2,  3,  4],
       [ 6,  7,  8],
       [10, 11, 12]])

---
# Boolean 인덱싱

In [9]:
myTF = [True, False, True]

In [10]:
arr[myTF]

IndexError: ignored

In [13]:
myTF = [True, False, True, True, False, True, True, False, True]

In [14]:
arr[myTF]

array([10,  2,  7, 65, 22, 70])

In [15]:
arr2d[arr2d % 2 == 0]

array([ 2,  4,  6,  8, 10, 12])

---
# range와 arange

In [16]:
arr = np.arange(1, 11)

In [17]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [18]:
arr = np.arange(start=1, stop=11)

In [19]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])