<a href="https://colab.research.google.com/github/mazdah/colab_practice/blob/main/%ED%8C%A8%EC%8A%A4%ED%8A%B8%EC%BA%A0%ED%8D%BC%EC%8A%A4_%EC%A7%81%EC%9E%A5%EC%9D%B8%EC%9D%84_%EC%9C%84%ED%95%9C_%ED%8C%8C%EC%9D%B4%EC%8D%AC_%EB%8D%B0%EC%9D%B4%ED%84%B0%EB%B6%84%EC%84%9D.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
np

<module 'numpy' from '/usr/local/lib/python3.7/dist-packages/numpy/__init__.py'>

In [3]:
arr = np.array([1, 2, 3, 4], dtype=int)

In [4]:
arr

array([1, 2, 3, 4])

In [5]:
type(arr)

numpy.ndarray

In [6]:
mylist1 = [1, 2, 3, 4]

In [7]:
mylist2 = [[1, 2, 3, 4],
           [5, 6, 7, 8]]

In [8]:
arr1 = np.array(mylist1)
arr2 = np.array(mylist2)

In [9]:
arr1.shape

(4,)

In [10]:
arr2.shape

(2, 4)

- list는 서로 다른 데이터 타입이 함께 조재할 수 있으나
- array는 모든 요소의 데이터 타입이 동일해야 한다

In [11]:
mylist = [1, 3.14, "문자열", (2, 3)]

In [12]:
mylist

[1, 3.14, '문자열', (2, 3)]

In [13]:
type(mylist)

list

In [14]:
arr = np.array([1, 2, 3.14, 2.12])

In [15]:
arr

array([1.  , 2.  , 3.14, 2.12])

In [16]:
arr2 = np.array([1, 2, 3.14, 2.12], dtype=int)

In [17]:
arr2

array([1, 2, 3, 2])

In [21]:
arr3 = np.array([1, 2, "3.14", 2.12])

In [22]:
arr3

array(['1', '2', '3.14', '2.12'], dtype='<U21')

In [23]:
arr3 = np.array([1, 2, "3.14", 2.12], dtype=int)

ValueError: ignored

In [24]:
arr3 = np.array([1, 2, "1234", 2.12], dtype=int)

In [25]:
arr3

array([   1,    2, 1234,    2])

In [26]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
arr.shape

(10,)

# index를 이용한 색인 

In [28]:
arr[-1]

9

In [29]:
arr[-11]

IndexError: ignored

In [35]:
arr2d = np.array([[1, 2, 3, 4],
         [5, 6, 7, 8],
         [9, 10, 11, 12]])

In [36]:
arr2d[1, 1]

6

# 범위 색인

In [38]:
arr[3:]

array([3, 4, 5, 6, 7, 8, 9])

In [39]:
arr[:5]

array([0, 1, 2, 3, 4])

In [40]:
arr[1:5]

array([1, 2, 3, 4])

In [41]:
arr[:-1]

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [42]:
arr2d[1, :]

array([5, 6, 7, 8])

In [43]:
arr2d[:, 1]

array([ 2,  6, 10])

In [44]:
arr2d[:2, :]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [45]:
arr2d[1:, :2]

array([[ 5,  6],
       [ 9, 10]])