<a href="https://colab.research.google.com/github/mazdah/colab_practice/blob/main/%ED%8C%A8%EC%8A%A4%ED%8A%B8%EC%BA%A0%ED%8D%BC%EC%8A%A4_%EC%A7%81%EC%9E%A5%EC%9D%B8%EC%9D%84_%EC%9C%84%ED%95%9C_%ED%8C%8C%EC%9D%B4%EC%8D%AC_%EB%8D%B0%EC%9D%B4%ED%84%B0%EB%B6%84%EC%84%9D.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
np

<module 'numpy' from '/usr/local/lib/python3.7/dist-packages/numpy/__init__.py'>

In [ ]:
arr = np.array([1, 2, 3, 4], dtype=int)

In [ ]:
arr

array([1, 2, 3, 4])

In [ ]:
type(arr)

numpy.ndarray

In [ ]:
mylist1 = [1, 2, 3, 4]

In [ ]:
mylist2 = [[1, 2, 3, 4],
           [5, 6, 7, 8]]

In [ ]:
arr1 = np.array(mylist1)
arr2 = np.array(mylist2)

In [ ]:
arr1.shape

(4,)

In [ ]:
arr2.shape

(2, 4)

- list는 서로 다른 데이터 타입이 함께 조재할 수 있으나
- array는 모든 요소의 데이터 타입이 동일해야 한다

In [ ]:
mylist = [1, 3.14, "문자열", (2, 3)]

In [ ]:
mylist

[1, 3.14, '문자열', (2, 3)]

In [ ]:
type(mylist)

list

In [ ]:
arr = np.array([1, 2, 3.14, 2.12])

In [ ]:
arr

array([1.  , 2.  , 3.14, 2.12])

In [ ]:
arr2 = np.array([1, 2, 3.14, 2.12], dtype=int)

In [ ]:
arr2

array([1, 2, 3, 2])

In [ ]:
arr3 = np.array([1, 2, "3.14", 2.12])

In [ ]:
arr3

array(['1', '2', '3.14', '2.12'], dtype='<U21')

In [ ]:
arr3 = np.array([1, 2, "3.14", 2.12], dtype=int)

ValueError: ignored

In [ ]:
arr3 = np.array([1, 2, "1234", 2.12], dtype=int)

In [ ]:
arr3

array([   1,    2, 1234,    2])

In [ ]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr.shape

(10,)

# index를 이용한 색인 

In [ ]:
arr[-1]

9

In [ ]:
arr[-11]

IndexError: ignored

In [ ]:
arr2d = np.array([[1, 2, 3, 4],
         [5, 6, 7, 8],
         [9, 10, 11, 12]])

In [ ]:
arr2d[1, 1]

6

---
# 범위 색인

In [ ]:
arr[3:]

array([3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr[:5]

array([0, 1, 2, 3, 4])

In [ ]:
arr[1:5]

array([1, 2, 3, 4])

In [ ]:
arr[:-1]

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
arr2d[1, :]

array([5, 6, 7, 8])

In [ ]:
arr2d[:, 1]

array([ 2,  6, 10])

In [ ]:
arr2d[:2, :]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
arr2d[1:, :2]

array([[ 5,  6],
       [ 9, 10]])

---
# 팬시 인덱싱

In [ ]:
arr = np.array([10, 28, 2, 7, 90, 65, 22, 66, 70])

In [ ]:
idx = [1, 3, 5]

In [ ]:
arr[idx]

array([28,  7, 65])

In [ ]:
arr2d = np.array([[1, 2, 3, 4],
                  [5, 6, 7, 8],
                  [9, 10, 11, 12]])

In [ ]:
arr2d[[0, 1], :]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
arr2d[:, [1,2,3]]

array([[ 2,  3,  4],
       [ 6,  7,  8],
       [10, 11, 12]])

---
# Boolean 인덱싱

In [ ]:
myTF = [True, False, True]

In [ ]:
arr[myTF]

IndexError: ignored

In [ ]:
myTF = [True, False, True, True, False, True, True, False, True]

In [ ]:
arr[myTF]

array([10,  2,  7, 65, 22, 70])

In [ ]:
arr2d[arr2d % 2 == 0]

array([ 2,  4,  6,  8, 10, 12])

---
# range와 arange

In [ ]:
arr = np.arange(1, 11)

In [ ]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
arr = np.arange(start=1, stop=11)

In [ ]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
np.arange(1, 11, 3)

array([ 1,  4,  7, 10])

In [ ]:
for i in range(1, 11, 3):
    print(i)

1
4
7
10


---
### Sorting (정렬)

In [ ]:
arr = np.array([1, 10, 5, 8, 2, 4, 3, 6, 8, 7, 9])

In [ ]:
arr

array([ 1, 10,  5,  8,  2,  4,  3,  6,  8,  7,  9])

In [ ]:
np.sort(arr)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  8,  9, 10])

In [ ]:
np.sort(arr)[::-1]

array([10,  9,  8,  8,  7,  6,  5,  4,  3,  2,  1])

In [ ]:
arr

array([ 1, 10,  5,  8,  2,  4,  3,  6,  8,  7,  9])

In [ ]:
arr2 = np.sort(arr)

In [ ]:
arr2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  8,  9, 10])

- 아래의 방법은 원본을 정렬 상태로 바꾼다.

In [ ]:
arr.sort()

In [ ]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  8,  9, 10])

In [ ]:
arr2d = np.array([[7, 5, 8, 6],
                  [3, 1, 2, 4],
                  [10, 9, 12, 11]])

In [ ]:
np.sort(arr2d, axis=1)

array([[ 5,  6,  7,  8],
       [ 1,  2,  3,  4],
       [ 9, 10, 11, 12]])

In [ ]:
np.sort(arr2d, axis=0)

array([[ 3,  1,  2,  4],
       [ 7,  5,  8,  6],
       [10,  9, 12, 11]])

In [ ]:
np.sort(arr2d)

array([[ 5,  6,  7,  8],
       [ 1,  2,  3,  4],
       [ 9, 10, 11, 12]])

---
### argsort

- 값이 아닌 index를 리턴

In [ ]:
np.argsort(arr2d, axis=1)

array([[1, 3, 0, 2],
       [1, 2, 0, 3],
       [1, 0, 3, 2]])

In [ ]:
np.argsort(arr2d, axis=0)

array([[1, 1, 1, 1],
       [0, 0, 0, 0],
       [2, 2, 2, 2]])

---
### 행렬 (matrix)

In [ ]:
import numpy as np

In [ ]:
a = np.array([[1, 2, 3],
              [2, 3, 4]])

In [ ]:
b = np.array([[4, 5, 6],
              [1, 2, 3]])

In [ ]:
a + b

array([[5, 7, 9],
       [3, 5, 7]])

In [ ]:
c = np.array([[1, 2],
              [3, 4],
              [5, 6]])

In [ ]:
b + c

ValueError: ignored

---
### sum
---

In [ ]:
# 각 행의 같은 열끼리 더함
np.sum(a, axis=0)

array([3, 5, 7])

In [ ]:
# 각 행 내의 모든 요소를 더함
np.sum(a, axis=1)

array([6, 9])

---
### 뺄셈
---

In [ ]:
a-b

array([[-3, -3, -3],
       [ 1,  1,  1]])

---
### 일반 곱셈
---

In [ ]:
a.shape, b.shape

((2, 3), (2, 3))

In [ ]:
a * b

array([[ 4, 10, 18],
       [ 2,  6, 12]])

---
### dot product
---

In [ ]:
np.dot(a, b)

ValueError: ignored

In [ ]:
a.shape, c.shape

((2, 3), (3, 2))

In [ ]:
np.dot(a, c)

array([[22, 28],
       [31, 40]])

In [ ]:
a.dot(c)

array([[22, 28],
       [31, 40]])

---
### broadcasting
---

In [ ]:
a + 3

array([[4, 5, 6],
       [5, 6, 7]])

In [ ]:
a - 1

array([[0, 1, 2],
       [1, 2, 3]])

In [ ]:
a * 2

array([[2, 4, 6],
       [4, 6, 8]])

In [ ]:
a / 3

array([[0.33333333, 0.66666667, 1.        ],
       [0.66666667, 1.        , 1.33333333]])

---
# 데이터 분석의 시작, 전처리 라이브러리

### ▶︎ pandas

- 데이터 분석을 위한 패키지
- series : 1차원으로 이루어진 데이터 배열 (컬럼)
- DataFrame : 2차원으로 이루어진 데이터 배열
---

In [1]:
import pandas as pd

pd.__version__

'1.1.5'

In [ ]:
pd.Series([1, 2, 3, 4])

0    1
1    2
2    3
3    4
dtype: int64

In [ ]:
a = [1, 2, 3, 4]
pd.Series(a)

0    1
1    2
2    3
3    4
dtype: int64

In [ ]:
company1 = [["삼성", 2000, "스마트폰"],
            ["현대", 1000, "자동차"],
            ["네이버", 500, "포털"]]

In [ ]:
pd.DataFrame(company1)

0     1     2
0   삼성  2000  스마트폰
1   현대  1000   자동차
2  네이버   500    포털

In [ ]:
df1 = pd.DataFrame(company1)
df1

0     1     2
0   삼성  2000  스마트폰
1   현대  1000   자동차
2  네이버   500    포털

In [ ]:
df1.columns = ["기업명", "매출", "업종"]
df1

기업명    매출    업종
0   삼성  2000  스마트폰
1   현대  1000   자동차
2  네이버   500    포털

In [ ]:
company2 = {"기업명": ["삼성", "현대", "네이버"],
            "매출액": [2000, 1000, 500],
            "업종": ["스마트폰", "자동차", "포털"]}

In [ ]:
df2 = pd.DataFrame(company2)
df2

기업명   매출액    업종
0   삼성  2000  스마트폰
1   현대  1000   자동차
2  네이버   500    포털

In [ ]:
df1.index = df1["기업명"]
df1

기업명    매출    업종
기업명                 
삼성    삼성  2000  스마트폰
현대    현대  1000   자동차
네이버  네이버   500    포털

In [ ]:
df1["매출"]

기업명
삼성     2000
현대     1000
네이버     500
Name: 매출, dtype: int64

In [ ]:
type(df1["매출"])

pandas.core.series.Series

---
### ▶︎ CSV 파일 읽어오기
---

In [ ]:
from google.colab import files

myfile = files.upload()

Saving korean-idol.csv to korean-idol (1).csv


---
### ▶︎ excel 파일 읽어오기
---

In [ ]:
import pandas as pd

pd.read_excel('./korean-idol.xlsx')

이름     그룹      소속사  성별       생년월일      키 혈액형   브랜드평판지수
0     지민  방탄소년단      빅히트  남자 1995-10-13  173.6   A  10523260
1   지드래곤     빅뱅       YG  남자 1988-08-18  177.0   A   9916947
2   강다니엘    NaN      커넥트  남자 1996-12-10  180.0   A   8273745
3      뷔  방탄소년단      빅히트  남자 1995-12-30  178.0  AB   8073501
4     화사    마마무      RBW  여자 1995-07-23  162.1   A   7650928
5     정국  방탄소년단      빅히트  남자 1997-09-01  178.0   A   5208335
6     민현   뉴이스트     플레디스  남자 1995-08-09  182.3   O   4989792
7     소연    아이들       큐브  여자 1998-08-26    NaN   B   4668615
8      진  방탄소년단      빅히트  남자 1992-12-04  179.2   O   4570308
9    하성운     핫샷  스타크루이엔티  남자 1994-03-22  167.1   A   4036489
10    태연   소녀시대       SM  여자 1989-03-09    NaN   A   3918661
11   차은우   아스트로     판타지오  남자 1997-03-30  183.0   B   3506027
12    백호   뉴이스트     플레디스  남자 1995-07-21  175.0  AB   3301654
13    JR   뉴이스트     플레디스  남자 1995-06-08  176.0   O   3274137
14    슈가  방탄소년단      빅히트  남자 1993-03-09  174.0   O   2925442

---
### ▶︎ 통계값, 요약, 정보, 정렬
---

In [2]:
df = pd.read_csv('./korean-idol.csv')
df

이름     그룹      소속사  성별        생년월일      키 혈액형   브랜드평판지수
0     지민  방탄소년단      빅히트  남자  1995-10-13  173.6   A  10523260
1   지드래곤     빅뱅       YG  남자  1988-08-18  177.0   A   9916947
2   강다니엘    NaN      커넥트  남자  1996-12-10  180.0   A   8273745
3      뷔  방탄소년단      빅히트  남자  1995-12-30  178.0  AB   8073501
4     화사    마마무      RBW  여자  1995-07-23  162.1   A   7650928
5     정국  방탄소년단      빅히트  남자  1997-09-01  178.0   A   5208335
6     민현   뉴이스트     플레디스  남자  1995-08-09  182.3   O   4989792
7     소연    아이들       큐브  여자  1998-08-26    NaN   B   4668615
8      진  방탄소년단      빅히트  남자  1992-12-04  179.2   O   4570308
9    하성운     핫샷  스타크루이엔티  남자  1994-03-22  167.1   A   4036489
10    태연   소녀시대       SM  여자  1989-03-09    NaN   A   3918661
11   차은우   아스트로     판타지오  남자  1997-03-30  183.0   B   3506027
12    백호   뉴이스트     플레디스  남자  1995-07-21  175.0  AB   3301654
13    JR   뉴이스트     플레디스  남자  1995-06-08  176.0   O   3274137
14    슈가  방탄소년단      빅히트  남자  1993-03-09  174.0   O   2925442

In [ ]:
df.columns

Index(['이름', '그룹', '소속사', '성별', '생년월일', '키', '혈액형', '브랜드평판지수'], dtype='object')

In [ ]:
new_cols = ['name', '그룹', '소속사', '성별', '생년월일', '키', '혈액형', '브랜드평판지수']
df.columns = new_cols
df

name     그룹      소속사  성별        생년월일      키 혈액형   브랜드평판지수
0     지민  방탄소년단      빅히트  남자  1995-10-13  173.6   A  10523260
1   지드래곤     빅뱅       YG  남자  1988-08-18  177.0   A   9916947
2   강다니엘    NaN      커넥트  남자  1996-12-10  180.0   A   8273745
3      뷔  방탄소년단      빅히트  남자  1995-12-30  178.0  AB   8073501
4     화사    마마무      RBW  여자  1995-07-23  162.1   A   7650928
5     정국  방탄소년단      빅히트  남자  1997-09-01  178.0   A   5208335
6     민현   뉴이스트     플레디스  남자  1995-08-09  182.3   O   4989792
7     소연    아이들       큐브  여자  1998-08-26    NaN   B   4668615
8      진  방탄소년단      빅히트  남자  1992-12-04  179.2   O   4570308
9    하성운     핫샷  스타크루이엔티  남자  1994-03-22  167.1   A   4036489
10    태연   소녀시대       SM  여자  1989-03-09    NaN   A   3918661
11   차은우   아스트로     판타지오  남자  1997-03-30  183.0   B   3506027
12    백호   뉴이스트     플레디스  남자  1995-07-21  175.0  AB   3301654
13    JR   뉴이스트     플레디스  남자  1995-06-08  176.0   O   3274137
14    슈가  방탄소년단      빅히트  남자  1993-03-09  174.0   O   2925442

In [ ]:
df.index

RangeIndex(start=0, stop=15, step=1)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 8 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   name     15 non-null     object 
 1   그룹       14 non-null     object 
 2   소속사      15 non-null     object 
 3   성별       15 non-null     object 
 4   생년월일     15 non-null     object 
 5   키        13 non-null     float64
 6   혈액형      15 non-null     object 
 7   브랜드평판지수  15 non-null     int64  
dtypes: float64(1), int64(1), object(6)
memory usage: 1.1+ KB


In [ ]:
# 수치형 데이터에 대해서만 정보가 나옴
df.describe()

키       브랜드평판지수
count   13.000000  1.500000e+01
mean   175.792308  5.655856e+06
std      5.820576  2.539068e+06
min    162.100000  2.925442e+06
25%    174.000000  3.712344e+06
50%    177.000000  4.668615e+06
75%    179.200000  7.862214e+06
max    183.000000  1.052326e+07

In [ ]:
df.shape

(15, 8)

In [ ]:
df.head()

name     그룹  소속사  성별        생년월일      키 혈액형   브랜드평판지수
0    지민  방탄소년단  빅히트  남자  1995-10-13  173.6   A  10523260
1  지드래곤     빅뱅   YG  남자  1988-08-18  177.0   A   9916947
2  강다니엘    NaN  커넥트  남자  1996-12-10  180.0   A   8273745
3     뷔  방탄소년단  빅히트  남자  1995-12-30  178.0  AB   8073501
4    화사    마마무  RBW  여자  1995-07-23  162.1   A   7650928

In [ ]:
df.tail()

name     그룹   소속사  성별        생년월일      키 혈액형  브랜드평판지수
10   태연   소녀시대    SM  여자  1989-03-09    NaN   A  3918661
11  차은우   아스트로  판타지오  남자  1997-03-30  183.0   B  3506027
12   백호   뉴이스트  플레디스  남자  1995-07-21  175.0  AB  3301654
13   JR   뉴이스트  플레디스  남자  1995-06-08  176.0   O  3274137
14   슈가  방탄소년단   빅히트  남자  1993-03-09  174.0   O  2925442

In [ ]:
df.head(3)

name     그룹  소속사  성별        생년월일      키 혈액형   브랜드평판지수
0    지민  방탄소년단  빅히트  남자  1995-10-13  173.6   A  10523260
1  지드래곤     빅뱅   YG  남자  1988-08-18  177.0   A   9916947
2  강다니엘    NaN  커넥트  남자  1996-12-10  180.0   A   8273745

In [ ]:
df.tail(2)

name     그룹   소속사  성별        생년월일      키 혈액형  브랜드평판지수
13   JR   뉴이스트  플레디스  남자  1995-06-08  176.0   O  3274137
14   슈가  방탄소년단   빅히트  남자  1993-03-09  174.0   O  2925442

In [ ]:
df.sort_index()

name     그룹      소속사  성별        생년월일      키 혈액형   브랜드평판지수
0     지민  방탄소년단      빅히트  남자  1995-10-13  173.6   A  10523260
1   지드래곤     빅뱅       YG  남자  1988-08-18  177.0   A   9916947
2   강다니엘    NaN      커넥트  남자  1996-12-10  180.0   A   8273745
3      뷔  방탄소년단      빅히트  남자  1995-12-30  178.0  AB   8073501
4     화사    마마무      RBW  여자  1995-07-23  162.1   A   7650928
5     정국  방탄소년단      빅히트  남자  1997-09-01  178.0   A   5208335
6     민현   뉴이스트     플레디스  남자  1995-08-09  182.3   O   4989792
7     소연    아이들       큐브  여자  1998-08-26    NaN   B   4668615
8      진  방탄소년단      빅히트  남자  1992-12-04  179.2   O   4570308
9    하성운     핫샷  스타크루이엔티  남자  1994-03-22  167.1   A   4036489
10    태연   소녀시대       SM  여자  1989-03-09    NaN   A   3918661
11   차은우   아스트로     판타지오  남자  1997-03-30  183.0   B   3506027
12    백호   뉴이스트     플레디스  남자  1995-07-21  175.0  AB   3301654
13    JR   뉴이스트     플레디스  남자  1995-06-08  176.0   O   3274137
14    슈가  방탄소년단      빅히트  남자  1993-03-09  174.0   O   2925442

In [ ]:
df.sort_index(ascending=False)

name     그룹      소속사  성별        생년월일      키 혈액형   브랜드평판지수
14    슈가  방탄소년단      빅히트  남자  1993-03-09  174.0   O   2925442
13    JR   뉴이스트     플레디스  남자  1995-06-08  176.0   O   3274137
12    백호   뉴이스트     플레디스  남자  1995-07-21  175.0  AB   3301654
11   차은우   아스트로     판타지오  남자  1997-03-30  183.0   B   3506027
10    태연   소녀시대       SM  여자  1989-03-09    NaN   A   3918661
9    하성운     핫샷  스타크루이엔티  남자  1994-03-22  167.1   A   4036489
8      진  방탄소년단      빅히트  남자  1992-12-04  179.2   O   4570308
7     소연    아이들       큐브  여자  1998-08-26    NaN   B   4668615
6     민현   뉴이스트     플레디스  남자  1995-08-09  182.3   O   4989792
5     정국  방탄소년단      빅히트  남자  1997-09-01  178.0   A   5208335
4     화사    마마무      RBW  여자  1995-07-23  162.1   A   7650928
3      뷔  방탄소년단      빅히트  남자  1995-12-30  178.0  AB   8073501
2   강다니엘    NaN      커넥트  남자  1996-12-10  180.0   A   8273745
1   지드래곤     빅뱅       YG  남자  1988-08-18  177.0   A   9916947
0     지민  방탄소년단      빅히트  남자  1995-10-13  173.6   A  10523260

In [ ]:
df.sort_values(by="키", ascending=False)

name     그룹      소속사  성별        생년월일      키 혈액형   브랜드평판지수
11   차은우   아스트로     판타지오  남자  1997-03-30  183.0   B   3506027
6     민현   뉴이스트     플레디스  남자  1995-08-09  182.3   O   4989792
2   강다니엘    NaN      커넥트  남자  1996-12-10  180.0   A   8273745
8      진  방탄소년단      빅히트  남자  1992-12-04  179.2   O   4570308
3      뷔  방탄소년단      빅히트  남자  1995-12-30  178.0  AB   8073501
5     정국  방탄소년단      빅히트  남자  1997-09-01  178.0   A   5208335
1   지드래곤     빅뱅       YG  남자  1988-08-18  177.0   A   9916947
13    JR   뉴이스트     플레디스  남자  1995-06-08  176.0   O   3274137
12    백호   뉴이스트     플레디스  남자  1995-07-21  175.0  AB   3301654
14    슈가  방탄소년단      빅히트  남자  1993-03-09  174.0   O   2925442
0     지민  방탄소년단      빅히트  남자  1995-10-13  173.6   A  10523260
9    하성운     핫샷  스타크루이엔티  남자  1994-03-22  167.1   A   4036489
4     화사    마마무      RBW  여자  1995-07-23  162.1   A   7650928
7     소연    아이들       큐브  여자  1998-08-26    NaN   B   4668615
10    태연   소녀시대       SM  여자  1989-03-09    NaN   A   3918661

In [ ]:
df.sort_values(by=["키", "name"])

name     그룹      소속사  성별        생년월일      키 혈액형   브랜드평판지수
4     화사    마마무      RBW  여자  1995-07-23  162.1   A   7650928
9    하성운     핫샷  스타크루이엔티  남자  1994-03-22  167.1   A   4036489
0     지민  방탄소년단      빅히트  남자  1995-10-13  173.6   A  10523260
14    슈가  방탄소년단      빅히트  남자  1993-03-09  174.0   O   2925442
12    백호   뉴이스트     플레디스  남자  1995-07-21  175.0  AB   3301654
13    JR   뉴이스트     플레디스  남자  1995-06-08  176.0   O   3274137
1   지드래곤     빅뱅       YG  남자  1988-08-18  177.0   A   9916947
3      뷔  방탄소년단      빅히트  남자  1995-12-30  178.0  AB   8073501
5     정국  방탄소년단      빅히트  남자  1997-09-01  178.0   A   5208335
8      진  방탄소년단      빅히트  남자  1992-12-04  179.2   O   4570308
2   강다니엘    NaN      커넥트  남자  1996-12-10  180.0   A   8273745
6     민현   뉴이스트     플레디스  남자  1995-08-09  182.3   O   4989792
11   차은우   아스트로     판타지오  남자  1997-03-30  183.0   B   3506027
7     소연    아이들       큐브  여자  1998-08-26    NaN   B   4668615
10    태연   소녀시대       SM  여자  1989-03-09    NaN   A   3918661

---
### ▶︎ Selection - column 선택
---

In [ ]:
df["name"]

0       지민
1     지드래곤
2     강다니엘
3        뷔
4       화사
5       정국
6       민현
7       소연
8        진
9      하성운
10      태연
11     차은우
12      백호
13      JR
14      슈가
Name: name, dtype: object

In [ ]:
type(df["name"])

pandas.core.series.Series

In [ ]:
df.혈액형

0      A
1      A
2      A
3     AB
4      A
5      A
6      O
7      B
8      O
9      A
10     A
11     B
12    AB
13     O
14     O
Name: 혈액형, dtype: object

---
### ▶︎ 범위 선택
---

In [3]:
df[:3]

이름     그룹  소속사  성별        생년월일      키 혈액형   브랜드평판지수
0    지민  방탄소년단  빅히트  남자  1995-10-13  173.6   A  10523260
1  지드래곤     빅뱅   YG  남자  1988-08-18  177.0   A   9916947
2  강다니엘    NaN  커넥트  남자  1996-12-10  180.0   A   8273745

In [4]:
df.loc[:, '이름']

0       지민
1     지드래곤
2     강다니엘
3        뷔
4       화사
5       정국
6       민현
7       소연
8        진
9      하성운
10      태연
11     차은우
12      백호
13      JR
14      슈가
Name: 이름, dtype: object

In [5]:
df.loc[:, ['이름', '생년월일']]

이름        생년월일
0     지민  1995-10-13
1   지드래곤  1988-08-18
2   강다니엘  1996-12-10
3      뷔  1995-12-30
4     화사  1995-07-23
5     정국  1997-09-01
6     민현  1995-08-09
7     소연  1998-08-26
8      진  1992-12-04
9    하성운  1994-03-22
10    태연  1989-03-09
11   차은우  1997-03-30
12    백호  1995-07-21
13    JR  1995-06-08
14    슈가  1993-03-09

In [6]:
df.loc[3:8, ['이름', '생년월일']]

이름        생년월일
3   뷔  1995-12-30
4  화사  1995-07-23
5  정국  1997-09-01
6  민현  1995-08-09
7  소연  1998-08-26
8   진  1992-12-04

In [7]:
df.loc[3:8, '이름':'생년월일']

이름     그룹   소속사  성별        생년월일
3   뷔  방탄소년단   빅히트  남자  1995-12-30
4  화사    마마무   RBW  여자  1995-07-23
5  정국  방탄소년단   빅히트  남자  1997-09-01
6  민현   뉴이스트  플레디스  남자  1995-08-09
7  소연    아이들    큐브  여자  1998-08-26
8   진  방탄소년단   빅히트  남자  1992-12-04

---
- **pandas의 loc는 마지막 인덱스를 포함한 값을 가져온다.**
- **하지만 iloc에서는 마지막 인덱스를 포함하지 않는다!!!**
---

In [8]:
df.iloc[2:5, [0, 2]]

이름  소속사
2  강다니엘  커넥트
3     뷔  빅히트
4    화사  RBW

In [10]:
df.iloc[2:5, 0:3]

이름     그룹  소속사
2  강다니엘    NaN  커넥트
3     뷔  방탄소년단  빅히트
4    화사    마마무  RBW

---
### ▶︎ boolean indexing
---

In [11]:
df['키'] > 180

0     False
1     False
2     False
3     False
4     False
5     False
6      True
7     False
8     False
9     False
10    False
11     True
12    False
13    False
14    False
Name: 키, dtype: bool

In [12]:
df[df['키'] > 180]

이름    그룹   소속사  성별        생년월일      키 혈액형  브랜드평판지수
6    민현  뉴이스트  플레디스  남자  1995-08-09  182.3   O  4989792
11  차은우  아스트로  판타지오  남자  1997-03-30  183.0   B  3506027

In [14]:
df[df['키'] > 180][['이름', '키']]

이름      키
6    민현  182.3
11  차은우  183.0

In [16]:
df.loc[df['키'] > 180, '이름':'키']

이름    그룹   소속사  성별        생년월일      키
6    민현  뉴이스트  플레디스  남자  1995-08-09  182.3
11  차은우  아스트로  판타지오  남자  1997-03-30  183.0

In [18]:
my_condition = ['플란다스', 'SM']

In [19]:
df.loc[df['소속사'].isin(my_condition)]

이름    그룹 소속사  성별        생년월일   키 혈액형  브랜드평판지수
10  태연  소녀시대  SM  여자  1989-03-09 NaN   A  3918661